---

- name: selinux | packages | install
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - policycoreutils-python
    - libselinux-python


- selinux:
    policy: targeted
    state: enforcing

- seboolean:
    name: "{{ item.key }}"
    state: "{{ item.value }}"
    persistent: yes
  with_dict: "{{ selinux_booleans | default({}) }}"
