---

- name: consul | firewalld | create client ipset
  include_role:
    name: firewalld
    tasks_from: ipset
  vars:
    ipset_name: consul_clients
    ipset_description: "Consul client nodes"
    ipset_entries: "{{ groups['all']}}"
  tags:
    - consul
    - firewalld


- name: consul | firewalld | create server ipset
  include_role:
    name: firewalld
    tasks_from: ipset
  vars:
    ipset_name: consul_servers
    ipset_description: "Consul server nodes"
    ipset_entries: "{{ groups['consul_servers']}}"
  tags:
    - consul
    - firewalld


- name: consul | firewalld | create rule for lan client gossip
  firewalld:
    rich_rule: "rule source ipset='consul_clients' port port='8301' protocol='{{ item }}'  audit limit value='15/m' accept"
    zone: public
    permanent: true
    state: enabled
  with_items:
    - "tcp"
    - "udp"
  notify:
    - firewalld | policy | reload
  tags:
    - consul
    - firewall

- name: consul | firewalld| create rule for wan server gossip
  firewalld:
    rich_rule: "rule source ipset='consul_servers' port port='8302' protocol='{{ item }}'  audit limit value='15/m' accept"
    zone: public
    permanent: true
    state: enabled
  when: "consul_server"
  notify:
    - firewalld | policy | reload
  with_items:
    - "tcp"
    - "udp"
  tags:
    - consul
    - firewall

- name: consul | firewalld | create rule for lan clients to lan servers
  firewalld:
    rich_rule: "rule source ipset='consul_clients' port port='8300' protocol='tcp'  audit limit value='30/m' accept"
    zone: public
    permanent: true
    state: enabled
  when: "consul_server"
  notify:
    - firewalld | policy | reload
  tags:
    - consul
    - firewall


- name: consul | firewalld | create rule for consul server services
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  when: "consul_server"
  with_items:
    - "8500/tcp"
    - "8600/udp"
    - "8600/tcp"
  tags:
    - consul
    - firewall

