---


# This will do for now

- name: pdns | firewalld | create rules
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  with_items:
    - "53/tcp"
    - "53/udp"
  notify:
    - firewalld | policy | reload
  tags:
    - dns
    - pdns
    - firewalld
