---

- name: pdns | recursor | packages | install
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ pdns_recursor_packages }}"
  tags:
    - dns
    - pdns
    - recursor

- name: pdns | recursor | service | enable and run
  service:
    name: "{{ pdns_recursor_service }}"
    state: running
    enabled: yes
  tags:
    - dns
    - pdns
    - recursor
