---

- name: auditd | packages | install
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ auditd_packages }}"
  tags:
    - audit

- name: auditd | config | create directories
  file:
    name: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "1700"
  with_items:
    - /etc/audit/
    - /etc/audit/rules.d
  tags:
    - audit

- name: auditd | config | create auditd.conf
  template:
    src: auditd.conf.j2
    dest: /etc/audit/auditd.conf
    owner: root
    group: root
    mode: "0600"
  tags:
    - audit

- name: auditd | rules | add base ruleset
  template:
    src: 00-auditd-base.rules.j2
    dest: /etc/audit/rules.d/00-auditd-base.rules
    owner: root
    group: root
    mode:  "0600"
  tags:
    - auditd

- name: auditd | rules | make ruleset immutable
  copy:
    dest: /etc/audit/rules.d/999-immutable.rules
    owner: root
    group: root
    mode:  "0600"
    content: "-e 2\n"
  tags:
    - auditd

- name: auditd | service | run and enable
  service:
    name: "{{ auditd_service_name }}"
    state: running
    enabled: yes
  tags:
    - audit
    - service


