---

- include_vars: "{{ ansible_os_family | lower }}.yml"
  ignore_errors: yes
  tags:
    - sysdig

- include: yum.yml
  when: "ansible_os_family == 'RedHat'"
  tags:
    - sysdig

- name: sysdig | packages | install
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - kernel-devel
    - sysdig
  tags:
    - sysdig

- include: falco.yml
  when: "sysdig_include_falco | default(True)"
