---

- name: sysdig | repo | configure
  yum_repository:
    name: draios
    state: present
    description: "Draios/sysdig repo"
    baseurl: "http://download.draios.com/stable/rpm/$basearch"
    gpgcheck: yes
    gpgkey: https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public
  tags:
    - sysdig
    - redhat
