---

- name: common | sysctl | reload
  command: /sbin/sysctl --load --system
  tags:
    - sysctl

- name: common | packages | update all
  package:
    name: "*"
    state: latest
  tags:
    - update
    - software


- include: timesyncd.yml
