---

- name: fail2ban | suricata | create filters
  template:
    src: "{{ item }}.conf.j2"
    dest: "/etc/fail2ban/filter.d/{{ item }}.conf"
    owner: root
    group: root
    mode: "0600"
  with_items:
    - suricata-badactors
    - suricata-prio1
  tags:
    - suricata
    - fail2ban


- name: fail2ban | suricata | create jail
  template:
    src: jail.suricata.j2
    dest: /etc/fail2ban/jail.d/suricata.conf
    owner: root
    group: root
    mode: "0600"
  notify:
    - fail2ban | service | restart
  tags:
    - suricata
    - fail2ban
