---

- include_vars: arm.yml
  when: "'arm' in ansible_architecture"
  tags:
    - prometheus
    - monitoring


- name: prometheus | group | create
  group:
    name: "{{ prometheus_group }}"
    state: present
  tags:
    - prometheus
    - monitoring



- name: prometheus | directories | create
  file:
    name: "{{ item }}"
    state: directory
    owner: root
    group: "{{ prometheus_group }}"
    mode: "1750"
  with_items:
    - /opt/prometheus
    - /opt/prometheus/bin
    - /opt/prometheus/data
    - /opt/prometheus/releases
    - /opt/prometheus/exporters
    - /etc/prometheus
    - /etc/prometheus/rules
    - /etc/prometheus/jobs
    - /etc/prometheus/sd
    - /etc/prometheus/exporters
  tags:
    - prometheus
    - monitoring



- include: server.yml
  when: "'prometheus_server' in group_names"

- include: alertmanager.yml
  when: "'prometheus_alertmanager' in group_names"

- include: node_exporter.yml

- include: haproxy_exporter.yml
  when: "'load_balancer' in group_names"
