- name:  firewalld | ipset | create {{ ipset_name }}
  template:
    src: firewalld.ipset.xml.j2
    dest: "/etc/firewalld/ipsets/{{ ipset_name }}.xml"
    owner: root
    group: root
    mode: "0640"
  notify:
    - firewalld | service | restart
  tags:
    - firewalld
