---

- include_vars: "{{ ansible_os_family | lower }}.yml"
  ignore_errors: yes
  tags:
    - docker

- include: yum.yml
  when: "ansible_os_family == 'RedHat'"
  tags:
    - docker

- name: docker | packages | install
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ docker_packages }}"
  tags:
    - docker


- name: docker | service | enable and run
  service:
    name: "{{ docker_service_name }}"
    state: running
    enabled: yes
  tags:
    - docker
    - service
