---


- hosts: all
  roles:
    - {role: selinux, when: "ansible_os_family == 'RedHat'"}
    - common
    - hardening
    - {role: 'firewalld', when: "not skip_firewalld"}
    - {role: 'suricata', when: 'not skip_ids'}
    - fail2ban
    - openssh
    - {role: auditd, when: "not skip_auditd"}
    - {role: sysdig, when: "not skip_sysdig"}
