---


- hosts: all
  roles:
    - {role: selinux, when: "ansible_os_family == 'RedHat'"}
    - common
    - hardening
    - {role: firewalld, when: "not skip_firewalld | default(False)"}
    - fail2ban
    - openssh
    - {role: auditd, when: "not skip_auditd | default(False)"}
    - {role: sysdig, when: "not skip_sysdig | default(False)"}
    - docker

- hosts: ids
  roles:
    - suricata
    - fail2ban
