---

# Installs agent on all nodes.
# Also configures required services for servers in consul_servers group.

- hosts: all
  roles:
    - {role: consul, when: "not skip_consul"}

- hosts:
    - etcd_servers
  roles:
    - etcd

- hosts:
    - dns_recursors
    - dns_authoritative
  roles:
    - pdns


# TODO: ntp
- hosts: ntp_servers
  roles: []
