---

- hosts: all
  roles:
    - {role: prometheus, when: "not skip_monitoring" }


- hosts:
    - prometheus_servers
    - prometheus_alertmanagers
  roles:
    - prometheus
    - {role: 'grafana', when: 'prometheus_server and not skip_grafana'}


# NOTE: In order to have dedicated grafana servers,
# it will typically be necessary to set prometheus_server_listen_address
# to something other than 127.0.0.1

- hosts:
    - grafana_servers
  roles:
    - grafana
